# Generated by Django 2.0.4 on 2018-04-10 10:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0002_auto_20180410_0434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', django_google_maps.fields.AddressField(max_length=100)),
                ('geolocation', django_google_maps.fields.GeoLocationField(blank=True, max_length=100)),
                ('createddate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipoactivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
        migrations.AddField(
            model_name='activo',
            name='tipoactivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mvc.Tipoactivo'),
        ),
    ]
